export const customFonts = {
  "Primary-100": require("../assets/fonts/Inter/Inter-ExtraLight.ttf"),
  "Primary-200": require("../assets/fonts/Inter/Inter-Light.ttf"),
  "Primary-300": require("../assets/fonts/Inter/Inter-Thin.ttf"),
  "Primary-400": require("../assets/fonts/Inter/Inter-Regular.ttf"),
  "Primary-500": require("../assets/fonts/Inter/Inter-Medium.ttf"),
  "Primary-600": require("../assets/fonts/Inter/Inter-SemiBold.ttf"),
  "Primary-700": require("../assets/fonts/Inter/Inter-Bold.ttf"),
  "Primary-800": require("../assets/fonts/Inter/Inter-ExtraBold.ttf"),
  "Primary-900": require("../assets/fonts/Inter/Inter-Black.ttf"),
  "Secondary-100": require("../assets/fonts/Comfortaa/Comfortaa-Light.ttf"),
  "Secondary-400": require("../assets/fonts/Comfortaa/Comfortaa-Regular.ttf"),
  "Secondary-500": require("../assets/fonts/Comfortaa/Comfortaa-Medium.ttf"),
  "Secondary-600": require("../assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf"),
  "Secondary-700": require("../assets/fonts/Comfortaa/Comfortaa-Bold.ttf"),
};
